select * from (
SELECT GNACT.IDACTIVITY, GNACT.NMACTIVITY, NULL AS STATUS, CASE WHEN GNSS.NMSURVEYSESSION IS NULL THEN CAST(GNSS.NRORDER AS VARCHAR(50)) ELSE CAST(GNSS.NRORDER AS VARCHAR(50)) + ' - ' + GNSS.NMSURVEYSESSION END AS NMSESSION, 0 AS NRONE, 0 AS FGSELECTED, CAST(GNQA.DSANSWER AS VARCHAR(MAX)) AS DSANSWER, CAST(NULL AS VARCHAR(50)) AS DSMATRIX, CAST(CAST(GNSS.NRORDER AS VARCHAR(50)) + '.' + CAST(GNSQ.NRORDER AS VARCHAR(50)) + ' ' + CAST(GNQ.DSQUESTION AS VARCHAR(MAX)) AS VARCHAR(MAX)) AS DSQUESTION, CAST(NULL AS VARCHAR(50)) AS DSOBSERVATION, GNQA.VLNOTE AS VLNOTEQUESTION
FROM GNSURVEYSESSION GNSS
INNER JOIN GNSURVEYQUESTION GNSQ ON (GNSQ.CDSURVEYSESSION=GNSS.CDSURVEYSESSION)
INNER JOIN GNQUESTION GNQ ON (GNQ.CDQUESTION=GNSQ.CDQUESTION) INNER JOIN GNQUESTIONANSWER GNQA ON (GNQA.CDQUESTION=GNQ.CDQUESTION) INNER JOIN GNSURVEY GNSRV ON (GNSRV.CDSURVEY=GNSQ.CDSURVEY)
INNER JOIN GNSURVEYEXEC GNSUREXEC ON (GNSUREXEC.CDSURVEY=GNSRV.CDSURVEY)
INNER JOIN SVSURVEY SRV ON (SRV.CDSURVEYEXEC=GNSUREXEC.CDSURVEYEXEC)
INNER JOIN GNACTIVITY GNACT ON (GNACT.CDGENACTIVITY=SRV.CDGENACTIVITY)
WHERE (GNACT.CDISOSYSTEM=214 AND GNQ.FGTYPEQUESTION IN (1, 2) AND NOT EXISTS (SELECT 1 FROM GNSURVEYEXECANSWER GNSA INNER JOIN GNSURVEXECQUESTION GNSEQ ON (GNSEQ.CDSURVEXECQUESTION=GNSA.CDSURVEXECQUESTION) WHERE GNSEQ.CDSURVEYEXEC IN (119) AND GNSA.FGSELECTED=1 AND GNSA.CDQUESTIONANSWER=GNQA.CDQUESTIONANSWER))
UNION ALL
SELECT GNACT.IDACTIVITY, GNACT.NMACTIVITY, CASE GNEXECUSR.FGSTATUS WHEN 1 THEN '#{100481}' WHEN 2 THEN '#{209659}' WHEN 3 THEN '#{100667}' WHEN 4 THEN '#{104919}' END AS STATUS, CASE WHEN GNSS.NMSURVEYSESSION IS NULL THEN CAST(GNSS.NRORDER AS VARCHAR(50)) ELSE CAST(GNSS.NRORDER AS VARCHAR(50)) + ' - ' + GNSS.NMSURVEYSESSION END AS NMSESSION, 1 AS NRONE, CASE WHEN GNSA.FGSELECTED=1 THEN 1 ELSE 0 END AS FGSELECTED, CAST(GNQA.DSANSWER AS VARCHAR(MAX)) AS DSANSWER, CAST(NULL AS VARCHAR(50)) AS DSMATRIX, CAST(CAST(GNSS.NRORDER AS VARCHAR(50)) + '.' + CAST(GNSQ.NRORDER AS VARCHAR(50)) + ' ' + CAST(GNQ.DSQUESTION AS VARCHAR(MAX)) AS VARCHAR(MAX)) AS DSQUESTION, CAST(GNSA.DSOBSERVATION AS VARCHAR(MAX)) AS DSOBSERVATION, GNQA.VLNOTE AS VLNOTEQUESTION
FROM GNSURVEYEXECANSWER GNSA
INNER JOIN GNSURVEXECQUESTION GNSEQ ON (GNSEQ.CDSURVEXECQUESTION=GNSA.CDSURVEXECQUESTION)
INNER JOIN GNSURVEYQUESTION GNSQ ON (GNSQ.CDSURVEYQUESTION=GNSEQ.CDSURVEYQUESTION)
INNER JOIN GNSURVEYSESSION GNSS ON (GNSS.CDSURVEYSESSION=GNSQ.CDSURVEYSESSION)
INNER JOIN GNQUESTION GNQ ON (GNQ.CDQUESTION=GNSQ.CDQUESTION)
INNER JOIN GNQUESTIONANSWER GNQA ON (GNQA.CDQUESTION=GNQ.CDQUESTION AND GNSA.CDQUESTIONANSWER=GNQA.CDQUESTIONANSWER)
INNER JOIN GNSURVEYEXECUSER GNEXECUSR ON (GNEXECUSR.CDSURVEYEXECUSER=GNSEQ.CDSURVEYEXECUSER)
INNER JOIN (SELECT GNSU2.CDSURVEYEXECUSER, CAST(ROW_NUMBER() OVER (PARTITION BY GNSU2.CDSURVEYEXEC, CASE WHEN GNSU2.FGSTATUS <> 4 AND GN.FGANONYMOUSSURVEY=1 THEN 1 END ORDER BY GNSU2.CDSURVEYEXECUSER) AS VARCHAR(255)) AS NRORDER FROM GNSURVEYEXECUSER GNSU2 INNER JOIN SVSURVEY SV ON (SV.CDSURVEYEXEC=GNSU2.CDSURVEYEXEC) INNER JOIN GNSURVEY GN ON (GN.CDSURVEY=SV.CDSURVEY) INNER JOIN GNSURVEYEXEC GNS ON (GNS.CDSURVEYEXEC=GNSU2.CDSURVEYEXEC) WHERE GNS.CDSURVEY IN (254)) TEMPORDERANO ON (TEMPORDERANO.CDSURVEYEXECUSER=GNEXECUSR.CDSURVEYEXECUSER)
INNER JOIN GNSURVEY GNSRV ON (GNSRV.CDSURVEY=GNSQ.CDSURVEY)
INNER JOIN SVSURVEY SRV ON (SRV.CDSURVEYEXEC=GNEXECUSR.CDSURVEYEXEC)
INNER JOIN GNACTIVITY GNACT ON (GNACT.CDGENACTIVITY=SRV.CDGENACTIVITY) LEFT JOIN ADALLUSERS AUSER ON (AUSER.CDUSER=GNEXECUSR.CDUSER)
WHERE (GNACT.CDISOSYSTEM=214 AND GNQ.FGTYPEQUESTION IN (1, 2) AND GNSA.FGSELECTED=1)
) _sub where idactivity like 'ITSM-SAT-%'
