SELECT 
 W.IDPROCESSMODEL AS 'IDModelo'
,W.NMPROCESSMODEL AS 'Modelo'
,W.IDPROCESSTYPE AS 'Tipo'
,W.IDPROCESS AS 'ID'
,W.NMPROCESS AS 'Instancia'
,W.CDUSERSTART AS 'Codigo'
,W.NMUSERSTART AS 'Usuario'
,W.DTSTART AS 'Inicio'
,D.NMDEPARTMENT AS 'Departamento'
,S.NMPOSITION AS 'Funcao'

FROM WFPROCESS W
LEFT JOIN ADUSERDEPTPOS DP ON DP.CDUSER = W.CDUSERSTART AND DP.FGDEFAULTDEPTPOS = 1
LEFT JOIN ADDEPARTMENT D ON D.CDDEPARTMENT = DP.CDDEPARTMENT
LEFT JOIN ADPOSITION S ON S.CDPOSITION = DP.CDPOSITION
WHERE YEAR(W.DTSTART)>=2019
