select sum(horas) as horas, usr.nmuser as analista, usr.idlogin as login, timesheetcomp.DTACTUAL
FROM aduser usr
inner join (
SELECT TIMESHEETVIEW.DTACTUAL, TIMESHEETVIEW.NMRESOURCE, TIMESHEETVIEW.cduser
, cast((cast(Datepart(hh,(DATEADD(ms, (COALESCE (CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTSTRAIGHTMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=2 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0) + COALESCE(CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTOVERMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=1 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0)) % 1000, DATEADD(ss, (COALESCE (CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTSTRAIGHTMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=2 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0) + COALESCE(CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTOVERMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=1 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0))/1000, CONVERT(DATETIME2(3),'19700101')))))*3600 as float) + cast(Datepart(mi,(DATEADD(ms, (COALESCE (CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTSTRAIGHTMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=2 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0) + COALESCE(CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTOVERMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=1 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0)) % 1000, DATEADD(ss, (COALESCE (CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTSTRAIGHTMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=2 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0) + COALESCE(CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTOVERMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=1 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0))/1000, CONVERT(DATETIME2(3),'19700101')))))*60 as float)+ cast(Datepart(ss,(DATEADD(ms, (COALESCE (CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTSTRAIGHTMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=2 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0) + COALESCE(CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTOVERMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=1 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0)) % 1000, DATEADD(ss, (COALESCE (CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTSTRAIGHTMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=2 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0) + COALESCE(CASE WHEN FGOVER=0 THEN (CAST( TIMESHEETVIEW.QTOVERMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) ELSE CASE WHEN FGOVER=1 THEN (CAST( GTE.QTTOTALMIN AS NUMERIC(28,12)) * CAST( 60 * 1000 AS NUMERIC(28,12))) END END, 0))/1000, CONVERT(DATETIME2(3),'19700101'))))) as float)) / 3600 as float) as horas
FROM (
--Projeto
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, ATI.CDTASK AS CDACTIVITY, ATI.NMIDTASK AS IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN PRTASKTIMESHEET TASKTIME ON (TASKTIME.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN PRTASK ATI ON (ATI.CDTASK=TASKTIME.CDTASK)
LEFT OUTER JOIN PRTASKTYPE ATITYPE ON (ATI.CDTASKTYPE=ATITYPE.CDTASKTYPE)
INNER JOIN PRTASK ATB ON (ATI.CDBASETASK=ATB.CDTASK)
	LEFT JOIN (SELECT DISTINCT PVIEW.PR_CDTASK FROM (SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, UDP.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADUSERDEPTPOS UDP ON UDP.CDDEPARTMENT=ACCVIEW.CDDEPARTMENT  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=1
	/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
	SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, UDP.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADUSERDEPTPOS UDP ON UDP.CDPOSITION=ACCVIEW.CDPOSITION  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=2
	/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
	SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, UDP.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADUSERDEPTPOS UDP ON UDP.CDDEPARTMENT=ACCVIEW.CDDEPARTMENT AND UDP.CDPOSITION=ACCVIEW.CDPOSITION  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=3
	/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
	SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, ACCVIEW.CDUSER FROM PRTASKACCESS ACCVIEW  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=4
	/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
	SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, TMM.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADTEAMUSER TMM ON TMM.CDTEAM=ACCVIEW.CDTEAM  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=5
	) PVIEW WHERE 1=1) PRTASKSECURITY ON PRTASKSECURITY.PR_CDTASK=ATB.CDBASETASK AND ATB.FGRESTRICT=1
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
WHERE ATI.FGTASKTYPE=1

UNION ALL
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, GNA.CDGENACTIVITY AS CDACTIVITY, GNA.IDACTIVITY AS IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN GNACTIVITYTSHEET GNTS ON (GNTS.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
INNER JOIN GNACTIVITY GNA ON (GNA.CDGENACTIVITY=GNTS.CDGENACTIVITY)
INNER JOIN GNACTIVITYTIMECFG GNCFG ON (GNA.CDACTIVITYTIMECFG=GNCFG.CDACTIVITYTIMECFG)
INNER JOIN ASEXECACTIVITY ASEXECACT ON (GNA.CDGENACTIVITY=ASEXECACT.CDGENACTIVITY)
LEFT JOIN ASPLANACTIVITY ASPLANACT ON (ASPLANACT.CDPLANACTIVITY=ASEXECACT.CDPLANNING)
INNER JOIN ASACTIVITY ASACT ON (ASEXECACT.CDACTIVITY=ASACT.CDACTIVITY)
WHERE ASEXECACT.FGACTTYPE=1

UNION ALL
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, GNA.CDGENACTIVITY AS CDACTIVITY, GNA.IDACTIVITY AS IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN GNACTIVITYTSHEET GNTS ON (GNTS.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
INNER JOIN GNACTIVITY GNA ON (GNA.CDGENACTIVITY=GNTS.CDGENACTIVITY)
INNER JOIN GNACTIVITYTIMECFG GNCFG ON (GNA.CDACTIVITYTIMECFG=GNCFG.CDACTIVITYTIMECFG)
INNER JOIN ASEXECACTIVITY ASEXECACT ON (GNA.CDGENACTIVITY=ASEXECACT.CDGENACTIVITY)
LEFT JOIN ASPLANACTIVITY ASPLANACT ON (ASPLANACT.CDPLANACTIVITY=ASEXECACT.CDPLANNING)
INNER JOIN ASACTIVITY ASACT ON (ASEXECACT.CDACTIVITY=ASACT.CDACTIVITY)
WHERE ASEXECACT.FGACTTYPE=3

UNION ALL
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, GNA.CDGENACTIVITY AS CDACTIVITY, GNA.IDACTIVITY AS IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN GNACTIVITYTSHEET GNTS ON (GNTS.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
INNER JOIN GNACTIVITY GNA ON (GNA.CDGENACTIVITY=GNTS.CDGENACTIVITY)
INNER JOIN GNACTIVITYTIMECFG GNCFG ON (GNA.CDACTIVITYTIMECFG=GNCFG.CDACTIVITYTIMECFG)
INNER JOIN ASEXECACTIVITY ASEXECACT ON (GNA.CDGENACTIVITY=ASEXECACT.CDGENACTIVITY)
LEFT JOIN ASPLANACTIVITY ASPLANACT ON (ASPLANACT.CDPLANACTIVITY=ASEXECACT.CDPLANNING)
INNER JOIN ASACTIVITY ASACT ON (ASEXECACT.CDACTIVITY=ASACT.CDACTIVITY)
WHERE ASEXECACT.FGACTTYPE IN (2,6,7,8)

--Plano de ação
UNION ALL
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, GNA.CDGENACTIVITY AS CDACTIVITY, GNA.IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN GNACTIVITYTSHEET GNTS ON (GNTS.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
INNER JOIN GNACTIVITY GNA ON (GNA.CDGENACTIVITY=GNTS.CDGENACTIVITY)
INNER JOIN GNTASK GNTK ON (GNA.CDGENACTIVITY=GNTK.CDGENACTIVITY)
LEFT OUTER JOIN GNGENTYPE GNGNTP ON (GNGNTP.CDGENTYPE=GNTK.CDTASKTYPE)
LEFT OUTER JOIN GNACTIVITY GNACT2 ON (GNACT2.CDGENACTIVITY=GNA.CDACTIVITYOWNER)
LEFT OUTER JOIN GNACTIONPLAN GNACTPL ON (GNACTPL.CDGENACTIVITY=GNACT2.CDGENACTIVITY)
LEFT OUTER JOIN GNGENTYPE GNGNTP2 ON (GNGNTP2.CDGENTYPE=GNACTPL.CDACTIONPLANTYPE)
INNER JOIN ADUSER ADUS ON (GNA.CDUSER=ADUS.CDUSER)
WHERE 1 = 1

UNION ALL
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, GNM.CDMEETING AS CDACTIVITY, GNM.IDMEETING AS IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN GNMEETINGTSHEET GMTS ON (GMTS.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN GNMEETING GNM ON (GNM.CDMEETING=GMTS.CDMEETING)
LEFT OUTER JOIN GNGENTYPE GNGT ON (GNM.CDMEETINGTYPE=GNGT.CDGENTYPE)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
WHERE 1 = 1

--Workflow
UNION ALL
SELECT GNTS.CDTIMESHEET, GNR.NMRESOURCE, GNTS.DTACTUAL, GNTS.CDUSER, GNTS.QTSTRAIGHTMIN, GNTS.QTOVERMIN
, GNTS.TMSTRAIGHTHOURS, GNTS.TMOVERHOURS, GNTS.QTTOTALMIN
, GNA.CDGENACTIVITY AS CDACTIVITY, WFS.IDSTRUCT AS IDACTIVITY
FROM GNACTIVITY GNA
INNER JOIN WFACTIVITY WFA ON (WFA.CDGENACTIVITY=GNA.CDGENACTIVITY)
INNER JOIN WFSTRUCT WFS ON (WFS.IDOBJECT=WFA.IDOBJECT)
INNER JOIN WFPROCESS WFP ON (WFP.IDOBJECT=WFS.IDPROCESS)
INNER JOIN GNACTIVITY GNAWF ON (GNAWF.CDGENACTIVITY=WFP.CDGENACTIVITY)
INNER JOIN GNACTIVITYTSHEET GNATS ON (GNATS.CDGENACTIVITY=GNA.CDGENACTIVITY)
INNER JOIN GNTIMESHEET GNTS ON (GNTS.CDTIMESHEET=GNATS.CDTIMESHEET)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=GNTS.CDRESOURCE)
WHERE (WFP.CDPRODAUTOMATION IS NULL OR WFP.CDPRODAUTOMATION NOT IN (275)) and wfp.fgstatus <> 3

UNION ALL
SELECT GNTS.CDTIMESHEET, GNR.NMRESOURCE, GNTS.DTACTUAL, GNTS.CDUSER, GNTS.QTSTRAIGHTMIN, GNTS.QTOVERMIN
, GNTS.TMSTRAIGHTHOURS, GNTS.TMOVERHOURS, GNTS.QTTOTALMIN
, GNA.CDGENACTIVITY AS CDACTIVITY, TSW.NMPREFIX + '-' + CAST(TST.NRTASK AS VARCHAR(255)) AS IDACTIVITY
FROM GNACTIVITY GNA
INNER JOIN WFPROCESS WFP ON (WFP.CDGENACTIVITY=GNA.CDGENACTIVITY)
INNER JOIN TSTASK TST ON (TST.IDOBJECT=WFP.IDOBJECT)
INNER JOIN TSWORKSPACE TSW ON (TSW.CDWORKSPACE=TST.CDWORKSPACE)
INNER JOIN TSFLOWSTEP TSFS ON (TSFS.CDFLOW=TST.CDFLOW AND TSFS.CDSTEP=TST.CDSTEP)
LEFT JOIN TSSPRINT TSS ON (TSS.CDSPRINT=TST.CDSPRINT AND TSS.CDWORKSPACE=TST.CDWORKSPACE)
INNER JOIN GNACTIVITYTSHEET GNATS ON (GNATS.CDGENACTIVITY=GNA.CDGENACTIVITY)
INNER JOIN GNTIMESHEET GNTS ON (GNTS.CDTIMESHEET=GNATS.CDTIMESHEET)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=GNTS.CDRESOURCE)
WHERE 1 = 1 and wfp.fgstatus <> 3

UNION ALL
SELECT TIMESHEET.CDTIMESHEET, GNR.NMRESOURCE AS NMRESOURCE, TIMESHEET.DTACTUAL, TIMESHEET.CDUSER, TIMESHEET.QTSTRAIGHTMIN, TIMESHEET.QTOVERMIN
, TIMESHEET.TMSTRAIGHTHOURS, TIMESHEET.TMOVERHOURS, TIMESHEET.QTTOTALMIN
, ATI.CDTASK AS CDACTIVITY, ATI.NMIDTASK AS IDACTIVITY
FROM GNTIMESHEET TIMESHEET
INNER JOIN PRTASKTIMESHEET TASKTIME ON (TASKTIME.CDTIMESHEET=TIMESHEET.CDTIMESHEET)
INNER JOIN PRTASK ATI ON (ATI.CDTASK=TASKTIME.CDTASK)
LEFT JOIN (SELECT DISTINCT PVIEW.PR_CDTASK FROM (SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, UDP.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADUSERDEPTPOS UDP ON UDP.CDDEPARTMENT=ACCVIEW.CDDEPARTMENT  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=1
/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, UDP.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADUSERDEPTPOS UDP ON UDP.CDPOSITION=ACCVIEW.CDPOSITION  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=2
/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, UDP.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADUSERDEPTPOS UDP ON UDP.CDDEPARTMENT=ACCVIEW.CDDEPARTMENT AND UDP.CDPOSITION=ACCVIEW.CDPOSITION  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=3
/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, ACCVIEW.CDUSER FROM PRTASKACCESS ACCVIEW  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=4
/*DONTREMOVE*/UNION ALL/*DONTREMOVE*/
SELECT ACCVIEW.CDTASK AS PR_CDTASK, ACCVIEW.FGACCESSCOST, TMM.CDUSER FROM PRTASKACCESS ACCVIEW INNER JOIN ADTEAMUSER TMM ON TMM.CDTEAM=ACCVIEW.CDTEAM  WHERE ACCVIEW.FGACCESS=1 AND ACCVIEW.FGTEAMMEMBER=5
) PVIEW WHERE 1=1) PRTASKSECURITY ON PRTASKSECURITY.PR_CDTASK=ATI.CDBASETASK AND ATI.FGRESTRICT=1 LEFT OUTER JOIN PRTASKTYPE ATITYPE ON (ATI.CDTASKTYPE=ATITYPE.CDTASKTYPE)
INNER JOIN GNRESOURCEVIEW GNR ON (GNR.CDRESOURCE=TIMESHEET.CDRESOURCE)
WHERE ATI.FGTASKTYPE IN (2, 3) AND (( ATI.FGRESTRICT=2 OR ATI.FGRESTRICT IS NULL OR ATI.FGRESTRICT=0) OR (PRTASKSECURITY.PR_CDTASK IS NOT NULL))
)TIMESHEETVIEW, GNTIMESHEET GTS, GNTIMEENTRY GTE
WHERE TIMESHEETVIEW.CDTIMESHEET=GTS.CDTIMESHEET AND GTE.CDTIMESHEET=TIMESHEETVIEW.CDTIMESHEET
) timesheetcomp on timesheetcomp.cduser = usr.cduser and year(timesheetcomp.DTACTUAL) = year(getdate()) and (month(timesheetcomp.DTACTUAL) = month(getdate()) or month(timesheetcomp.DTACTUAL) = month(getdate()) - 1)
where usr.FGUSERENABLED = 1
group by timesheetcomp.DTACTUAL, usr.nmuser, usr.idlogin
