SELECT REQ.OIDAPIREQUEST,
	   NMREQUESTURL,
       NMRESOURCEPATH,
       SUBSTRING(NMRESOURCEPATH, CHARINDEX('se/ws/', NMRESOURCEPATH) + 6, CHARINDEX('_', NMRESOURCEPATH)-(CHARINDEX('se/ws/', NMRESOURCEPATH) + 6)) AS COMPONENT,
       REQ.NRRESPONSECODE,
       DATEADD (SECOND, BNREQUESTDATETIME/1000, '1970-01-01 00:00:00') - (DATEDIFF(HOUR, GETDATE(), GETUTCDATE()) / 24.00000000000000000) as REQUESTDATETIME,
	   DATEADD (SECOND, BNRESPONSEDATETIME/1000, '1970-01-01 00:00:00') - (DATEDIFF(HOUR, GETDATE(), GETUTCDATE()) / 24.00000000000000000) as RESPONSEDATETIME,
       (FLOG.BNLOGDATETIME - BNREQUESTDATETIME) AS PREPARA_REQUEST,
       (LLOG.BNLOGDATETIME - FLOG.BNLOGDATETIME) AS BACKENDAPI,
       (BNRESPONSEDATETIME - LLOG.BNLOGDATETIME) AS PERSISTENCIA,
       (BNRESPONSEDATETIME - BNREQUESTDATETIME) AS TEMPO_TOTAL,
       1 AS QTD
FROM DIAPIREQUEST REQ
LEFT JOIN DIAPIREQUESTLOG FLOG ON FLOG.OIDAPIREQUEST = REQ.OIDAPIREQUEST
AND FLOG.FGLOG = 3
LEFT JOIN DIAPIREQUESTLOG LLOG ON LLOG.OIDAPIREQUEST = REQ.OIDAPIREQUEST
AND LLOG.FGLOG = 4
