SELECT
	TSBRND.CDSPRINT,
	TSBRND.BNDATE,
	TSBRND.VLTOTAL,
	TSBRND.VLREMAINING,
	TSBRND.VLEXPECTED,
	TSSPT.NMTITLE,
	TSSPT.BNSTART,
	TSSPT.BNFINISH,
	TSSPT.FGSTATUS,
	TSWK.CDWORKSPACE,
	TSWK.NMPREFIX,
	TSWK.NMWORKSPACE
FROM
	TSBURNDOWN TSBRND
	INNER JOIN TSSPRINT TSSPT ON (TSBRND.CDSPRINT = TSSPT.CDSPRINT)
	INNER JOIN TSWORKSPACE TSWK  ON (TSSPT.CDWORKSPACE = TSWK.CDWORKSPACE)
