SELECT
    ASAST.FGASSTATUS,
    CASE ASAST.FGASSTATUS
        WHEN 1 THEN '#{100303}'
        WHEN 2 THEN '#{102647}'
        WHEN 3 THEN '#{102646}'
        WHEN 4 THEN '#{104499}'
        WHEN 5 THEN '#{104232}'
        WHEN 6 THEN '#{102645}'
        WHEN 7 THEN '#{101556}'
        WHEN 10 THEN '#{100289}'
    END NM_FGSTATUS,
    OBOBJ.CDOBJECT,
    OBOBJ.IDOBJECT,
    OBOBJ.NMOBJECT,
    OBTY.CDOBJECTTYPE,
    OBTY.IDOBJECTTYPE,
    OBTY.NMOBJECTTYPE
FROM
    ASASSET ASAST
    INNER JOIN OBOBJECT OBOBJ ON ( ASAST.CDASSET = OBOBJ.CDOBJECT AND ASAST.CDREVISION = OBOBJ.CDREVISION )
    INNER JOIN OBOBJECTGROUP OBGRP ON ( OBOBJ.CDOBJECT = OBGRP.CDOBJECTGROUP )
    INNER JOIN OBOBJECTTYPE OBTY ON ( OBGRP.CDOBJECTTYPE = OBTY.CDOBJECTTYPE )
WHERE
    OBOBJ.FGCURRENT = 1
    AND EXISTS (
        SELECT 1
        FROM GNUSERPERMTYPEROLE CHKTYPEROLE
        WHERE
            CHKTYPEROLE.CDTYPEROLE = OBTY.CDTYPEROLE
            AND CDPERMISSION = 5
            AND CDUSER IN (-1, <!%CDUSER%>)
            AND FGPERMISSIONTYPE = 1
    )
    AND NOT EXISTS (
        SELECT 1
        FROM GNUSERPERMTYPEROLE CHKTYPEROLE
        WHERE
            CHKTYPEROLE.CDTYPEROLE = OBTY.CDTYPEROLE
            AND CDPERMISSION = 5
            AND CDUSER IN (-1, <!%CDUSER%>)
            AND FGPERMISSIONTYPE = 2
    )
