select H.CDUSERCODE,
	   H.IDLOGIN,
	   H.NMUSERNAME,
	   H.BNLOGINTIME,
	   H.SESSION_LOGIN,
	   H.SESSION_LOGOUT,
	   H.SESSION_DURATION,
	   H.CONCURRENT_USERS_LOGIN,
	   H.CONCURRENT_USERS_LOGOUT,
	   L.NMID LICENSE_NAME, 
       L.NRNUMBEROFUSERS LICENSE_MAX_USERS,
	   ADP.NMDEPARTMENT,
	   ADO.NMPOSITION,
	   1 AS QTD
 from (
	select CDUSERCODE, 
		   NMUSERNAME,
		   IDLOGIN, 
		   BNLOGINTIME, 
		   DATEADD(SECOND, (BNLOGINTIME/1000)+'<!%FUNC("com.softexpert.utils.TimeZoneHelper")%>' , '1970-01-01 00:00:00') SESSION_LOGIN,
		   DATEADD(SECOND, (BNLOGOUTTIME/1000)+'<!%FUNC("com.softexpert.utils.TimeZoneHelper")%>' , '1970-01-01 00:00:00') SESSION_LOGOUT,
		   BNLOGOUTTIME-BNLOGINTIME SESSION_DURATION, 
		   OIDLICENSEKEY,
		   NRCONCURRENTSESSIONLOGIN CONCURRENT_USERS_LOGIN,
		   NRCONCURRENTSESSION CONCURRENT_USERS_LOGOUT 
	  from SEUSERSESSIONLOG 
	 WHERE FGSESSIONTYPE=2 
	   AND OIDLICENSEKEY IS NOT NULL 
	   AND BNLOGOUTTIME IS NOT NULL
       AND NRCONCURRENTSESSIONLOGIN IS NOT NULL
	   AND BNLOGOUTTIME < 6890000000000
  ) as H 
LEFT OUTER JOIN COLICENSEKEY L ON (L.OID=H.OIDLICENSEKEY)
LEFT OUTER JOIN ADUSERDEPTPOS ADU on (ADU.CDUSER = H.CDUSERCODE)
LEFT OUTER JOIN ADDEPARTMENT ADP ON (ADU.CDDEPARTMENT=ADP.CDDEPARTMENT)
LEFT OUTER JOIN ADPOSITION ADO ON (ADU.CDPOSITION=ADO.CDPOSITION)
