SELECT
	WKS.CDWORKSPACE,
	WKS.NMWORKSPACE,
	WKS.NMPREFIX,
	TSTYPE.CDTASKTYPE,
	TSTYPE.NMTASKTYPE,
	PRT.CDPRIORITY,
	PRT.NMPRIORITY,
	TSSTEP.CDSTEP,
	TSSTEP.NMSTEP,
	CASE PROGHIST.FGTYPE
		WHEN 1 THEN CAST(3 AS VARCHAR(32)) + ' - ' + TSSTEP.NMSTEP
		WHEN 2 THEN CAST(1 AS VARCHAR(32)) + ' - ' + TSSTEP.NMSTEP
		WHEN 3 THEN CAST(2 AS VARCHAR(32)) + ' - ' + TSSTEP.NMSTEP
	END AS NMSTEP_ORDERED,
	PROGHIST.DTINSERT,
    PROGHIST.FGTYPE,
	CASE PROGHIST.FGTYPE
		WHEN 1 THEN '#{106947}'
		WHEN 2 THEN '#{305806}'
		WHEN 3 THEN '#{113363}'
	END AS NMTYPE,
	PROGHIST.QTQUANT,
        PROGHIST.FGENABLED
FROM
	TSPROGRESSHISTORY PROGHIST
	LEFT JOIN TSSTEP ON (TSSTEP.CDSTEP = PROGHIST.CDSTEP)
	LEFT JOIN TSTASKTYPE TSTYPE ON (TSTYPE.CDTASKTYPE = PROGHIST.CDTASKTYPE)
	LEFT JOIN TSPRIORITY PRT ON (PRT.CDPRIORITY = PROGHIST.CDPRIORITY)
	LEFT JOIN TSWORKSPACE WKS ON PROGHIST.CDWORKSPACE = WKS.CDWORKSPACE
