SELECT
C.*
FROM(
SELECT 
A.IDIDENTIFIER AS ID_ANALISE,
A.NMNAME AS NOME_ANALISE,
U.IDLOGIN AS OWNER,
A.NMUSERUPD AS MODIFIEDBY,
A.DTUPDATE AS MODIFIEDON,
A.DTINSERT AS CREATEDON,
T.TXDATA
FROM SETEXT T INNER JOIN BI2DATASETSQLQUERY D ON (T.OID=D.OIDCLOB)
INNER JOIN BI2ANALYSIS A ON (A.OID=D.OIDANALYSIS)
INNER JOIN GNPERMISSION G ON (G.OID=A.OIDPERMISSION)
INNER JOIN ADALLUSERS U ON (G.CDUSEROWNER=U.CDUSER)
WHERE T.TXDATA IS NOT NULL

group by 
A.IDIDENTIFIER,
A.NMNAME,
U.IDLOGIN,
A.NMUSERUPD,
A.DTUPDATE,
A.DTINSERT,
T.TXDATA)C
