SELECT
	SPR.CDWORKSPACE,
	TSWK.NMWORKSPACE,
	SPR.CDSPRINT,
	SPR.NMTITLE AS SPRINTTITLE,
        SPR.FGSTATUS,
    CASE
        WHEN SPR.FGSTATUS = 1 THEN '#{104919}'
        WHEN SPR.FGSTATUS = 2 THEN '#{100650}'
        WHEN SPR.FGSTATUS = 3 THEN '#{101237}'
        ELSE NULL
    END AS SPRINTSTATUS,
	SPR.BNSTART,
	SPR.BNFINISH,
	TSK.CDTASK,
	TSK.NMTITLE AS TASKTITLE,
    SPRHIST.FGTASKSTARTED,   
	CASE
		WHEN SPRHIST.FGTASKSTARTED = 1 THEN '#{100092}'
		ELSE '#{100093}'
	END AS TASKSTARTED,
    SPRHIST.FGTASKINCLUDED,
	CASE
		WHEN SPRHIST.FGTASKINCLUDED = 1 THEN '#{100092}'
		ELSE '#{100093}'
	END AS TASKINCLUDED,
    SPRHIST.FGTASKREMOVED,
	CASE
		WHEN SPRHIST.FGTASKREMOVED = 1 THEN '#{100092}'
		ELSE '#{100093}'
	END AS TASKREMOVED,
    SPRHIST.FGTASKCLOSED,
	CASE
		WHEN SPRHIST.FGTASKCLOSED = 1 THEN '#{100092}'
		ELSE '#{100093}'
	END AS TASKCLOSED,
	SPRHIST.VLESTIMATESTART,
	SPRHIST.VLESTIMATEFINSH,
	TSWK.NMPREFIX + '-' + CAST(TSK.NRTASK AS VARCHAR(50)) AS IDTASK,
	TSFLOW.CDFLOW,
	TSFLOW.NMFLOW,
	CREATEDBY.CDUSER AS CDCREATEDBY,
	CREATEDBY.IDUSER + '-' + CREATEDBY.NMUSER AS NMCREATEDBY,
	REPORTER.CDUSER AS CDREPORTER,
	REPORTER.IDUSER + '-' + REPORTER.NMUSER AS NMREPORTER,
	ASSIGNEE.CDUSER AS CDASSIGNEE,
	ASSIGNEE.IDUSER + '-' + ASSIGNEE.NMUSER AS NMASSIGNEE,
	TSK.DTINSERT,
	TSKTYPE.CDTASKTYPE,
	TSKTYPE.NMTASKTYPE,
	WKTEAM.CDTEAM AS CDWKTEAM,
	WKTEAM.IDTEAM + '-' + WKTEAM.NMTEAM AS WKTEAMRESPONSIBLE
FROM
	TSTASK TSK 
	INNER JOIN TSSPRINTHISTORY SPRHIST ON TSK.CDTASK = SPRHIST.CDTASK
	INNER JOIN TSSPRINT SPR ON SPR.CDSPRINT = SPRHIST.CDSPRINT
	INNER JOIN TSWORKSPACE TSWK ON TSWK.CDWORKSPACE = TSK.CDWORKSPACE
	INNER JOIN TSFLOW ON TSFLOW.CDFLOW = TSK.CDFLOW
	INNER JOIN TSTASKTYPE TSKTYPE ON TSKTYPE.CDTASKTYPE = TSK.CDTASKTYPE
	INNER JOIN ADTEAM WKTEAM ON WKTEAM.CDTEAM = TSWK.CDTEAMRESPONSIBLE
	INNER JOIN TSWORKSPACEPERM TSWKPERM ON TSWKPERM.CDWORKSPACE = TSWK.CDWORKSPACE
	LEFT JOIN ADUSER CREATEDBY ON CREATEDBY.CDUSER = TSK.CDCREATEDBY
	LEFT JOIN ADUSER REPORTER ON REPORTER.CDUSER = TSK.CDREPORTER
	LEFT JOIN ADUSER ASSIGNEE ON ASSIGNEE.CDUSER = TSK.CDASSIGNEE
WHERE
	(
        TSWKPERM.FGLISTPUBLIC = 1 
        OR ( TSWKPERM.FGLISTASSIGNEE = 1 AND TSK.CDASSIGNEE = <!%CDUSER%> )
        OR ( TSWKPERM.FGLISTREPORTER = 1 AND TSK.CDREPORTER = <!%CDUSER%> )
        OR EXISTS (
            SELECT 1
            FROM ADTEAMMEMBER ADTM
            WHERE 
                ADTM.CDTEAM = TSWK.CDTEAMRESPONSIBLE
                AND ADTM.CDUSER = <!%CDUSER%>
            UNION
            SELECT 1
            FROM ADTEAMMEMBER ADTM
            WHERE
                ADTM.CDTEAM = TSWK.CDTEAM
                AND ADTM.CDUSER = <!%CDUSER%>
                AND TSWKPERM.FGLISTTEAM = 1
        ) 
    )
