SELECT
	TSTASK.CDTASK,
	CONCAT(TSWORKSPACE.NMPREFIX, CONCAT('-', TSTASK.NRTASK)) IDTASK,
	TSTASK.NMTITLE,
	TSTASK.DTDEADLINE,
	TSWORKSPACE.NMWORKSPACE,
	ADUSER_CREATOR.IDUSER AS IDUSER_CREATOR,
	ADUSER_CREATOR.NMUSER AS NMUSER_CREATOR,
	ADUSER_REPORTER.IDUSER AS IDUSER_REPORTER,
	ADUSER_REPORTER.NMUSER AS NMUSER_REPORTER,
	ADUSER_ASSIGNEE.IDUSER AS IDUSER_ASSIGNEE,
	ADUSER_ASSIGNEE.NMUSER AS NMUSER_ASSIGNEE,
	TSSTEP.NMSTEP,
	CASE
		WHEN EXISTS(
			SELECT 1 
			FROM TSFLOWSTEP 
			WHERE 
				TSTASK.CDFLOW = TSFLOWSTEP.CDFLOW 
				AND TSTASK.CDSTEP = TSFLOWSTEP.CDSTEP 
				AND TSFLOWSTEP.FGTYPE = 2
		) THEN '#{100092}' -- Sim
		ELSE '#{100093}' -- Não
	END NMFINISHED,
        CASE
		WHEN EXISTS(
			SELECT 1 
			FROM TSFLOWSTEP 
			WHERE 
				TSTASK.CDFLOW = TSFLOWSTEP.CDFLOW 
				AND TSTASK.CDSTEP = TSFLOWSTEP.CDSTEP 
				AND TSFLOWSTEP.FGTYPE = 2
		) THEN 1
		ELSE 2
	END FGFINISHED,
	WFSTRUCT.NMSTRUCT AS NMSTEP_FLOW,
	(WFEXECACTIVITY.BNFINISH - WFEXECACTIVITY.BNENABLE) AS BNDURATION,
	DATEADD(SECOND, FLOOR(BNENABLE / 1000), '1970-01-01') DTENABLE,
	CASE
		WHEN BNFINISH IS NOT NULL THEN DATEADD(SECOND, FLOOR(BNFINISH / 1000), '1970-01-01')
		ELSE NULL
	END DTFINISH,
	TSTASKTYPE.NMTASKTYPE,
	TSPRIORITY.NMPRIORITY,
        TSWORKSPACE.CDWORKSPACE,
        TSTASKTYPE.CDTASKTYPE,
        TSPRIORITY.CDPRIORITY
FROM
	TSTASK
	INNER JOIN TSWORKSPACE ON TSTASK.CDWORKSPACE = TSWORKSPACE.CDWORKSPACE
	INNER JOIN TSTASKTYPE ON TSTASK.CDTASKTYPE = TSTASKTYPE.CDTASKTYPE
	INNER JOIN ADUSER ADUSER_CREATOR ON TSTASK.CDCREATEDBY = ADUSER_CREATOR.CDUSER
	INNER JOIN ADUSER ADUSER_REPORTER ON TSTASK.CDREPORTER = ADUSER_REPORTER.CDUSER
	LEFT JOIN ADUSER ADUSER_ASSIGNEE ON TSTASK.CDASSIGNEE = ADUSER_ASSIGNEE.CDUSER
	INNER JOIN TSSTEP ON TSTASK.CDSTEP = TSSTEP.CDSTEP
	INNER JOIN TSPRIORITY ON TSTASK.CDPRIORITY = TSPRIORITY.CDPRIORITY
	INNER JOIN WFEXECACTIVITY ON TSTASK.IDOBJECT = WFEXECACTIVITY.IDOBJWORKFLOW
	INNER JOIN WFSTRUCT ON WFEXECACTIVITY.IDOBJSTRUCT = WFSTRUCT.IDOBJECT
